language: perl
perl:
  - '5.8'
  - '5.10'
  - '5.12'
  - '5.14'
  - '5.16'
  - '5.18'
# Perl v5.19.4 thru v5.19.11 has an incompatible bug with Lingua::Stem::UniNE:
# https://rt.perl.org/Public/Bug/Display.html?id=121778
#  - '5.19'
before_install:
  cpanm -n Devel::Cover::Report::Coveralls
script:
  perl Build.PL && ./Build && cover -test -report coveralls
